export default {

    THEME_INIT: "THEME_INIT",     //初始化主题
    THEME_CHANGE: "THEME_CHANGE",    //更改主题


    USER_LOAIN: "USER_LOAIN",  //用户登录
    USER_UPDATE: "USER_UPDATE",  //用户更新
    USER_LOGOUT: "USER_LOGOUT",  //用户注销

    BOOKLIST_INIT: "BOOKLIST_INIT",  //书架初始化
    BOOKLIST_LOADING: "BOOKLIST_LOADING",  //书架加载

    COMMENT_REFRESH: "COMMENT_REFRESH",  //加载评论列表
    COMMENT_REFRESH_SUCCESS: "COMMENT_REFRESH_SUCCESS",  //加载成功
    COMMENT_REFRESH_FAIL: "COMMENT_REFRESH_FAIL",  //加载失败

}